### ISSUE TITLE
week 04/17

### ISSUE THREAD

**Issue by ebridge2** [NeuroDataDesign/fngs#12]
@ebridge2

- [x] for Thursday: test group-level qa with percent-retained (ie, retain highest 50% of edges, and threshold to 1 and remove below to 0), rank (replace value with the rank and use weighted network metrics) and squared-rank (ie, take rank, and square, to impose a more-sparse structure without totally removing small edges, again use weighted network metrics), as alternative to just thresholding by a absolute correlation value (what we are doing now). also, throw out really low things, but retain weights above. 
- [x] a few subjects of kara's data do not work. investigate why; correct where possible. [reg](https://neurodatadesign.github.io/fngs/ebridge2/new_reg/week_0417/registration_qa.html) [mc](https://neurodatadesign.github.io/fngs/ebridge2/new_reg/week_0417/motion_correction.html) [graph](https://neurodatadesign.github.io/fngs/ebridge2/new_reg/week_0417/aal-2mm.html). See [here](https://github.com/NeuroDataDesign/fngs/tree/master/docs/ebridge2/new_reg/week_0417) for specific examples of one good, and the worst-performing, subjects. Relatively consistent performance on these brains. 

- [x] add more qa statistics.

- [x] stretch: improve bids-crawl to work with non-complete sessions (ie, sessions that are missing anatomical, dwi, or functional data)

- [ ] Non FNGS goal: write presentation for thesis.

- [x] stretch: add slice timing correction to AWS batch deployment, and integrate tanay's cloud stuff/my adjustments to my working branch of ndmg. [cloud](https://github.com/neurodata/ndmg/blob/eric-dev-gkiar-fmri/ndmg/scripts/ndmg_cloud.py) 

- [x] stretch: adapt existing R package to work with CPAC data. [compare](https://neurodatadesign.github.io/fngs/ebridge2/fngs_merge/week_0416/fngs-vs-CPAC.html). Note that this is not populated, and the version of our pipeline is dated (from ~January, before we fixed nuisance and registration) but it will serve as a framework once we have AWS batch sorted out.

@ewalke31
- [x] for Thursday: begin working on preprocessing documentation
https://neurodatadesign.github.io/fngs/ewalke31/tutorials/week_0410/Preprocessing.html
- [x] for Monday: do Motion Correction & Registration documentation
https://neurodatadesign.github.io/fngs/ewalke31/tutorials/week_0410/Preprocessing.html
https://neurodatadesign.github.io/fngs/ewalke31/tutorials/week_0410/Registration.html

@02agarwalt
- [x] implement AWS Batch functionality for FNGS pipeline: [Link to relevant code](https://github.com/02agarwalt/ndmg/blob/eric-dev-gkiar-fmri/ndmg/scripts/ndmg_cloud.py)
(Proof of completion = demo)

**Comment by ebridge2** [comment]
- [ ] adjust bids-crawl to work with no session labels.

**Comment by jovo** [comment]
@ewalke31 documentation is looking great
@02agarwalt i trust the demo went well?
@ebridge2 nothing for me to look at?
