### ISSUE TITLE
error log: optimal, r4.xlarge, 1 desired vCPU

### ISSUE THREAD

**Issue by 02agarwalt** [NeuroDataDesign/fngs#17]

06:28:58
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more inf

06:28:58
SNIMissingWarning

06:28:58
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.htm

06:28:58
InsecurePlatformWarning

06:38:34
Retrieving data from S3...

06:38:34
['/ndmg_atlases/atlases/label/HarvardOxford-cort-maxprob-thr25-2mm.nii.gz', '/ndmg_atlases/atlases/label/aal-2mm.nii.gz', '/ndmg_atlases/atlases/label/brodmann-2mm.nii.gz', '/ndmg_atlases/atlases/label/desikan-2mm.nii.gz', '/ndmg_atlases/atlases/label/Talairach-2mm.nii.gz', '/ndmg_atlases/atlases/atlas/MNI152_T1-2mm.nii.gz', '/ndmg_atlases/atlases/mask/MNI152_T1-2mm_brain_mask.nii.gz', '/ndmg_atla

06:38:34
['/data/raw/sub-0025865/ses-1/anat/sub-0025865_ses-1_T1w.nii.gz']

06:38:34
['/data/raw/sub-0025865/ses-1/func/sub-0025865_ses-1_bold.nii.gz']

06:38:34
1

06:38:34
1

06:38:34
T1 file: /data/raw/sub-0025865/ses-1/anat/sub-0025865_ses-1_T1w.nii.gz

06:38:34
fMRI file: /data/raw/sub-0025865/ses-1/func/sub-0025865_ses-1_bold.nii.gz

06:38:34
Acquisition pattern: interleaved

06:38:34
This pipeline will produce the following derivatives...

06:38:34
fMRI volumes preprocessed: /data/outputs/reg/func/preproc/sub-0025865_ses-1_bold_preproc.nii.gz

06:38:34
fMRI volumes motion corrected: /data/outputs/reg/func/mc/sub-0025865_ses-1_bold_mc.nii.gz

06:38:34
fMRI volume registered to atlas: /data/outputs/reg/func/align/sub-0025865_ses-1_bold_aligned.nii.gz

06:38:34
Voxel timecourse in atlas space: /data/outputs/ts_voxel/sub-0025865_ses-1_bold_voxel.npz

06:38:34
ROI timeseries downsampled to given labels: /data/outputs/ts_roi/HarvardOxford-cort-maxprob-thr25-2mm/sub-0025865_ses-1_bold_HarvardOxford-cort-maxprob-thr25-2mm.npy, /data/outputs/ts_roi/aal-2mm/sub-0025865_ses-1_bold_aal-2mm.npy, /data/outputs/ts_roi/brodmann-2mm/sub-0025865_ses-1_bold_brodmann-2mm.npy, /data/outputs/ts_roi/desikan-2mm/sub-0025865_ses-1_bold_desikan-2mm.npy, /data/outputs/ts_roi

06:38:34
Connectomes downsampled to given labels: /data/outputs/connectomes/HarvardOxford-cort-maxprob-thr25-2mm/sub-0025865_ses-1_bold_HarvardOxford-cort-maxprob-thr25-2mm.gpickle, /data/outputs/connectomes/aal-2mm/sub-0025865_ses-1_bold_aal-2mm.gpickle, /data/outputs/connectomes/brodmann-2mm/sub-0025865_ses-1_bold_brodmann-2mm.gpickle, /data/outputs/connectomes/desikan-2mm/sub-0025865_ses-1_bold_desikan-

06:38:34
Preprocessing volumes...

06:38:34
Executing: slicetimer -i /data/raw/sub-0025865/ses-1/func/sub-0025865_ses-1_bold.nii.gz -o /data/outputs/tmp/sub-0025865_ses-1_bold_stc.nii.gz --odd -r 2.0

06:38:34
Executing: mcflirt -in /data/outputs/tmp/sub-0025865_ses-1_bold_stc.nii.gz -out /data/outputs/reg/func/mc/sub-0025865_ses-1_bold_mc.nii.gz -plots -refvol 0

06:38:34
Executing: cp /data/outputs/reg/func/mc/sub-0025865_ses-1_bold_mc.nii.gz /data/outputs/reg/func/preproc/sub-0025865_ses-1_bold_preproc.nii.gz

06:38:34
Performing QA for Preprocessing...

06:38:34
Aligning volumes...

06:38:34
Executing: bet /data/raw/sub-0025865/ses-1/anat/sub-0025865_ses-1_T1w.nii.gz /data/outputs/tmp/sub-0025865_ses-1_T1w_brain.nii.gz -f 0.3 -R -B -S

06:38:34
Executing: flirt -in /data/outputs/reg/func/preproc/sub-0025865_ses-1_bold_preproc.nii.gz -ref /data/outputs/tmp/sub-0025865_ses-1_T1w_brain.nii.gz -omat /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_xfm_epi2t1w_init1.mat -schedule ${FSLDIR}/etc/flirtsch/sch3Dtrans_3dof

06:38:34
Executing: flirt -in /data/outputs/reg/func/preproc/sub-0025865_ses-1_bold_preproc.nii.gz -ref /data/outputs/tmp/sub-0025865_ses-1_T1w_brain.nii.gz -omat /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_xfm_epi2t1w_init2.mat -schedule ${FSLDIR}/etc/flirtsch/simple3D.sch -init /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_xfm_epi2t1w_init1.mat

06:38:34
Executing: flirt -in /data/outputs/reg/func/preproc/sub-0025865_ses-1_bold_preproc.nii.gz -ref /data/outputs/tmp/sub-0025865_ses-1_T1w_brain.nii.gz -out /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_init.nii.gz -init /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_xfm_epi2t1w_init2.mat -interp trilinear -applyxfm

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_bids.py", line 284, in main

07:18:34
File "/usr/local/bin/ndmg_bids", line 11, in <module>

07:18:34
Executing: epi_reg --epi=/data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_init.nii.gz --t1=/data/raw/sub-0025865/ses-1/anat/sub-0025865_ses-1_T1w.nii.gz --t1brain=/data/outputs/tmp/sub-0025865_ses-1_T1w_brain.nii.gz --out=/data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_bbr.nii.gz

07:18:34
Analyzing Self Registration Quality...

07:18:34
Executing: bet /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_bbr.nii.gz /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_bbr_brain.nii.gz -f 0.3 -m

07:18:34
Executing: bet /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_init.nii.gz /data/outputs/tmp/sub-0025865_ses-1_bold_preproc_self-aligned_init_brain.nii.gz -f 0.3 -m

07:18:34
load_entry_point('ndmg==0.0.49', 'console_scripts', 'ndmg_bids')()

07:18:34
Traceback (most recent call last):

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_bids.py", line 150, in participant_level

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/scripts/ndmg_func_pipeline.py", line 146, in ndmg_func_pipeline

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 513, in register

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 420, in self_align

07:18:34
File "build/bdist.linux-x86_64/egg/ndmg/register/register.py", line 211, in resample

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 94, in save

07:18:34
img.to_filename(filename)

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/filebasedimages.py", line 338, in to_filename

07:18:34
self.to_file_map()

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/analyze.py", line 1069, in to_file_map

07:18:34
arr_writer.to_fileobj(imgf)

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/arraywriters.py", line 562, in to_fileobj

07:18:34
nan2zero=self._needs_nan2zero())

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/volumeutils.py", line 660, in array_to_file

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/volumeutils.py", line 833, in _write_data

07:18:34
pre_clips=pre_clips)

07:18:34
fileobj.write(dslice.tostring())

07:18:34
File "/usr/local/lib/python2.7/dist-packages/nibabel/openers.py", line 171, in write

07:18:34
return self.fobj.write(*args, **kwargs)

07:18:34
File "/usr/lib/python2.7/gzip.py", line 236, in write

07:18:34
self.fileobj.write( self.compress.compress(data) )

07:18:34
IOError: [Errno 28] No space left on device

**Comment by ebridge2** [comment]
DONE
